# Generated by Django 2.2.6 on 2020-03-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Write the desciption of your food item!')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_expires', models.DateField()),
            ],
        ),
    ]
